# Generated by Django 6.0.4 on 2026-04-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='cropclimate',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_climates', to='crop.crop'),
        ),
        migrations.AlterField(
            model_name='cropsoiltexture',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_soil_textures', to='crop.crop'),
        ),
    ]
