# Generated by Django 6.0.4 on 2026-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cropsoiltexture',
            name='unique_crop_soil',
        ),
        migrations.AddField(
            model_name='cropsoiltexture',
            name='texture_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cropsoiltexture',
            constraint=models.UniqueConstraint(fields=('crop', 'texture_name'), name='unique_crop_soil_name'),
        ),
        migrations.RemoveField(
            model_name='cropsoiltexture',
            name='soil_texture',
        ),
        migrations.DeleteModel(
            name='SoilTexture',
        ),
    ]
