# Generated by Django 6.0.3 on 2026-03-30 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_zone', models.CharField(default='', max_length=50)),
                ('mineralization_factor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_class', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('ph_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('ph_max', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('duration_Days', models.IntegerField(default=0)),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('water_min_mm', models.FloatField()),
                ('water_max_mm', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('n_kg_ha', models.FloatField()),
                ('p_kg_ha', models.FloatField()),
                ('k_kg_ha', models.FloatField()),
                ('soil_moisture', models.CharField(default='', max_length=50)),
                ('root_depth_cm', models.FloatField()),
                ('sampling_depth_cm', models.FloatField()),
                ('sampling_shape', models.CharField(default='', max_length=50)),
                ('sowing_month_start', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('sowing_month_end', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ph_min__lte', models.F('ph_max'))), name='ph_min_less_than_max'), models.CheckConstraint(condition=models.Q(('temp_min__lte', models.F('temp_max'))), name='temp_min_less_than_max'), models.CheckConstraint(condition=models.Q(('water_min_mm__lte', models.F('water_max_mm'))), name='water_min_less_than_max'), models.CheckConstraint(condition=models.Q(('humidity_min__lte', models.F('humidity_max'))), name='humidity_min_less_than_max'), models.CheckConstraint(condition=models.Q(('ph_min__gte', 0.0), ('ph_min__lte', 14.0)), name='ph_min_between_0_and_14'), models.CheckConstraint(condition=models.Q(('ph_max__gte', 0.0), ('ph_max__lte', 14.0)), name='ph_max_between_0_and_14')],
            },
        ),
        migrations.CreateModel(
            name='CropSoilTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_rank', models.IntegerField(choices=[(1, 'Avoid'), (2, 'Difficult'), (3, 'Acceptable'), (4, 'Good'), (5, 'Ideal')])),
                ('note', models.CharField(default='', max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('soil_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.soiltexture')),
            ],
        ),
        migrations.CreateModel(
            name='CropClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Avoid'), (2, 'Difficult'), (3, 'Acceptable'), (4, 'Good'), (5, 'Ideal')])),
                ('Note', models.CharField(default='', max_length=100)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.climate')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crop', 'climate'), name='unique_crop_climate')],
            },
        ),
    ]
