# Generated by Django 6.0.3 on 2026-03-24 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('n', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ph__gte', 0.0), ('ph__lte', 14.0)), name='ph_between_0_and_14')],
            },
        ),
    ]
