# Generated by Django 6.0.3 on 2026-03-29 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('PH_Min', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('PH_Max', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('Duration_Days', models.IntegerField(default=0)),
                ('Temp_Min', models.FloatField()),
                ('Temp_Max', models.FloatField()),
                ('Water_Min_mm', models.FloatField()),
                ('Water_Max_mm', models.FloatField()),
                ('Humidity_Min', models.FloatField()),
                ('Humidity_Max', models.FloatField()),
                ('N_kg_Ha', models.FloatField()),
                ('P_kg_Ha', models.FloatField()),
                ('K_kg_Ha', models.FloatField()),
                ('Root_Depth_cm', models.FloatField()),
                ('Sampling_Depth_cm', models.FloatField()),
                ('Sampling_Shape', models.CharField()),
                ('Sowing_Month_start', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('Sowing_Month_end', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('Note', models.CharField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('PH_Min__gte', 0.0), ('PH_Min__lte', 14.0)), name='ph_min_between_0_and_14'), models.CheckConstraint(condition=models.Q(('PH_Max__gte', 0.0), ('PH_Max__lte', 14.0)), name='ph_max_between_0_and_14')],
            },
        ),
    ]
