# Generated by Django 6.0.3 on 2026-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_remove_crop_soil_moisture'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
