# Generated by Django 6.0.3 on 2026-03-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_crop_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='root_depth_cm',
            new_name='root_depth_max_cm',
        ),
        migrations.AddField(
            model_name='crop',
            name='root_depth_min_cm',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
