# Generated by Django 6.0.3 on 2026-03-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('pk', models.BigAutoField(auto_created=True, blank=True, editable=False, primary_key=True, serialize=False)),
                ('Note', models.TextField(max_length=1000)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('recommendation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.recommendation')),
            ],
        ),
    ]

