# Generated by Django 6.0.3 on 2026-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('recommendation_id', 'crop_id')},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pk',
        ),
        migrations.AddField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),

    ]
