# Generated by Django 6.0.3 on 2026-03-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_plan_unique_together_plan_id_remove_plan_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
    ]
