# Generated by Django 5.2.13 on 2026-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_recommendationsession_soil_texture_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationsession',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='recommendationsession',
            constraint=models.UniqueConstraint(fields=('lat', 'lon'), name='unique_lat_lon'),
        ),
    ]
