# Generated by Django 6.0.4 on 2026-04-25 11:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('n_total_raw_ppm', models.FloatField(null=True)),
                ('p_extractable_raw_ppm', models.FloatField(null=True)),
                ('k_extractable_raw_ppm', models.FloatField(null=True)),
                ('soil_texture_initial', models.CharField(max_length=20)),
                ('soil_ph_initial', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('slope_angle', models.FloatField()),
                ('land_cover', models.CharField(max_length=50)),
                ('rainfall_avg', models.FloatField()),
                ('temperature_avg', models.FloatField()),
                ('humidity_avg', models.FloatField()),
                ('koppen', models.CharField(max_length=10)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.recommendationsession')),
            ],
        ),
    ]
