# Generated by Django 6.0.4 on 2026-04-27 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationsession',
            name='bulk_density',
            field=models.FloatField(blank=True, default=1.3, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='k_extractable_raw_ppm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='n_total_raw_ppm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='p_extractable_raw_ppm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
