# Generated by Django 6.0.3 on 2026-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsession',
            name='soil_texture_initial',
            field=models.CharField(max_length=20),
        ),
    ]
