# Generated by Django 6.0.4 on 2026-04-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_recommendationsession_soil_texture_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationsession',
            name='user',
        ),
    ]
