# Generated by Django 6.0.4 on 2026-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_recommendationsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsession',
            name='k_extractable_raw_ppm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='n_total_raw_ppm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendationsession',
            name='p_extractable_raw_ppm',
            field=models.FloatField(null=True),
        ),
    ]
