# Generated by Django 6.0.4 on 2026-04-23 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_coords', models.JSONField(help_text='List of coordinates [[lat, lon], ...]')),
                ('surface_area_m2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_analyses', to='recommendation.recommendationsession')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_name', models.CharField(max_length=50)),
                ('coverage_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('rescored_value', models.FloatField(blank=True, null=True)),
                ('field_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_textures', to='Field.fieldanalysis')),
            ],
        ),
    ]
