# Generated by Django 6.0.4 on 2026-05-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0002_remove_fieldanalysis_recommendation_session_and_more'),
        ('recommendation', '0002_recommendationsession_bulk_density_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFertilizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_percent', models.FloatField(blank=True, null=True)),
                ('p_percent', models.FloatField(blank=True, null=True)),
                ('k_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_available_kg_ha', models.FloatField(blank=True, null=True)),
                ('p_available_kg_ha', models.FloatField(blank=True, null=True)),
                ('k_available_kg_ha', models.FloatField(blank=True, null=True)),
                ('n_deficit_kg_ha', models.FloatField(blank=True, null=True)),
                ('p_deficit_kg_ha', models.FloatField(blank=True, null=True)),
                ('k_deficit_kg_ha', models.FloatField(blank=True, null=True)),
                ('crop_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_fertilization_history', to='recommendation.croprecommendation')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalizedFertilizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_percent', models.FloatField(blank=True, null=True)),
                ('p_percent', models.FloatField(blank=True, null=True)),
                ('k_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ph_entered', models.FloatField()),
                ('n_entered_ppm', models.FloatField()),
                ('p_entered_ppm', models.FloatField()),
                ('k_entered_ppm', models.FloatField()),
                ('n_total_kg', models.FloatField(blank=True, null=True)),
                ('p_total_kg', models.FloatField(blank=True, null=True)),
                ('k_total_kg', models.FloatField(blank=True, null=True)),
                ('ph_note', models.CharField(blank=True, max_length=100, null=True)),
                ('field_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_fertilization_history', to='Field.fieldanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
